/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'AutoDemo__core_createViewer_demo$vue': typeof import('./../core/createViewer/demo.vue')['default']
    'AutoDemo_core_createViewer_demo$vue': typeof import('./../core/createViewer/demo.vue')['default']
    DemoContainer: typeof import('./theme/components/demo-container.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
