/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CesiumContainer: typeof import('./theme/components/cesium-container.vue')['default']
    DemoContainer: typeof import('./theme/components/demo-container.vue')['default']
    HomeHeroImage: typeof import('./theme/components/home-hero-image.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
